### ISSUE TITLE
Command-line arguments are not read.

### ISSUE THREAD

**Issue by jchown** [jchown/YellowSnow#1]
This is due to a [Flutter issue](https://github.com/flutter/flutter/issues/32986)

**Comment by blurymind** [comment]
any luck on this?

**Comment by jchown** [comment]
I've not chased it up. It seems such an oversight by the Flutter team...

I'm going to spend some time fixing up things and trying out Flutter 2 towards the end of the month, surely now Canonical and Microsoft are supporting it ([ref](https://developers.googleblog.com/2021/03/announcing-flutter-2.html)) they have to fix it?!

**Comment by blurymind** [comment]
I think it was added on all platforms, its just poorly documented. Will give it a try in the weekend

**Comment by jchown** [comment]
I can't see how to get to the ``dart_entrypoint_arguments`` inside ``FlutterEngine`` (on the native side) so for now I've used FFI to read the arguments via Win32 APIs.
